Second pratice:

In [1]:
import numpy as np

In [5]:
np.__version__

'2.0.2'

In [8]:
list1=[2,4,6,7]
print(list1)

[2, 4, 6, 7]


In [ ]:
a=np.array(list1)
print(a)

[[2 4 6 7]]


In [11]:
print(type(a))

<class 'numpy.ndarray'>


In [31]:
print(a.ndim)

2


In [21]:
list2=[2,3,4,5]
a2=np.array([[2,3,4,5],[7,8,9,4]])
print(a2)

[[2 3 4 5]
 [7 8 9 4]]


In [22]:
print(a2.ndim)

2


In [28]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [29]:
print(a3.ndim)

3


In [40]:
arr1=np.array([[3,4,5],[5,6,7]])
print(arr1)

[[3 4 5]
 [5 6 7]]


In [42]:
print(arr1.shape)#row and column
print(arr1.size) #number of element
print(arr1.dtype)
print(arr1.ndim)

(2, 3)
6
int64
2


In [44]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [45]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [46]:
print(np.full((2,3),4))

[[4 4 4]
 [4 4 4]]


gdfdfdfgdg
