In [1]:
import numpy as np

In [3]:
print(np.__version__)

2.0.2


In [8]:
list1=[1,2,3]
list2=[2,4,6]
array1=np.array([list1,list2])
print(array1)




[[1 2 3]
 [2 4 6]]


In [9]:
print(array1.ndim)

2


In [12]:
print("shape",array1.shape)
print("size",array1.size)
print("N_dim",array1.ndim)

shape (2, 3)
size 6
N_dim 2


In [13]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
print(np.ones((3,3)))
array3=np.ones((3,3))
print(array3.ndim)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2


In [19]:
data=np.full((3,3),7)
print(data)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [26]:
#identiti matries
data=np.eye((3))
print(data)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
print(np.linspace(1,10,10))


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [40]:
np.random.randint(1,100,(3,3))

array([[31, 19, 58],
       [65,  7,  6],
       [74, 59, 89]], dtype=int32)

In [43]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [51]:
print(a[:,1])

[2 5]
